# /environments/local/docker-compose.yml
version: '3.8'

services:
  dockmaster:
    image: ${AUTH_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-auth
    volumes:
      - ${DOCKMASTER_KEY_PATH}:/app/keys/dockmaster.key:ro
    env_file:
      - ${DOCKMASTER_ENVFILE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - harbormaster

  dockyard:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    volumes:
      - ${DOCKYARD_KEY_PATH}:/app/keys/dockyard.key:ro
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - harbormaster
    depends_on:
      dockmaster:
        condition: service_healthy

  waypoint:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - harbormaster
    depends_on:
      dockyard:
        condition: service_healthy

  nginx:
    build:
      context: ../../nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ${NGINX_CONFIG_PATH:-./nginx.conf}:/etc/nginx/conf.d/environment/current.conf:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - harbormaster
    depends_on:
      waypoint:
        condition: service_healthy
      dockyard:
        condition: service_healthy
      dockmaster:
        condition: service_healthy

networks:
  harbormaster:
    name: ${COMPOSE_PROJECT_NAME}-network

volumes:
  backend_data:
    name: ${COMPOSE_PROJECT_NAME}-backend-data