# /environments/local/docker-compose.yml
version: '3.8'

services:
  dockmaster:
    image: ${AUTH_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-auth
    volumes:
      - ${DOCKMASTER_KEY_PATH}:/app/keys/dockmaster.key:ro
    env_file:
      - ${DOCKMASTER_ENVFILE_PATH}
    networks:
      - harbormaster
    ports:
      - "8001:8001"
    command: ["python", "-m", "uvicorn", "dockmaster.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]


  dockyard:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    volumes:
      - ${DOCKYARD_KEY_PATH}:/app/keys/dockyard.key:ro
      - backend_data:/app/data
    networks:
      - harbormaster
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "dockyard.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - dockmaster


  waypoint:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-true}
    networks:
      - harbormaster
    ports:
      - "3000:3000"
    depends_on:
      - dockmaster
      - dockyard

  nginx:
    build:
      context: ../../nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ${NGINX_CONFIG_PATH:-./nginx.conf}:/etc/nginx/conf.d/environment/current.conf:ro
    networks:
      - harbormaster
    environment:
      - NGINX_DEBUG=1
    command: ["nginx-debug", "-g", "daemon off;"] 
    # command: ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
    depends_on:
      - dockmaster
      - dockyard
      - waypoint

networks:
  harbormaster:
    name: ${COMPOSE_PROJECT_NAME}-network

volumes:
  backend_data:
    name: ${COMPOSE_PROJECT_NAME}-backend-data